---
title: "congress_manual"
author: "Carrie Hamilton"
date: "2024-07-22"
output: html_document
---

########need to combine and summarize full speech dataset, to find proportion from each year that are environmental speeches

########need to investigate why daily_descr has more entries than daily_speeches
########need to investigate why bound_descr has more entries than bound_speeches

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

options(repos = list(CRAN="http://cran.rstudio.com/"))
install.packages("pacman")
library(pacman)
p_load(tidyverse, congress, httr, federalregister, readxl, xml2, sparklyr, vroom, stopwords, data.table, tictoc)

```


```{r dictionaries, echo=FALSE}

# enviroVocab_v1 <- c("environmental movement",
#                     "environmentalism",
#                     "environmentalist",
#                     "environmental activi",
#                     "environmental organiz",
#                     "environmental group")
# # environmental activist, conservation, climate change,

enviroVocab <- c("environmental")




# laborVocab_v1 <- c("labor movement",
#                    "unionism",
#                    "unionist",
#                    "labor activi",
#                    "labor organiz",# "labor organization",
#                    "organized labor",
#                    "labor union",
#                    "trade union",
#                    "industrial union",
#                    "craft union")

laborVocab <- c("\\blabor\\b")






# enviroVocabString_v1 <- enviroVocab_v1 %>%
#   paste(collapse = "|") %>%
#   str_replace_all(" ","[:blank:]")
enviroVocabString <- enviroVocab %>%
  paste(collapse = "|") %>%
  str_replace_all(" ","[:blank:]")


# laborVocabString_v1 <- laborVocab_v1 %>%
#   paste(collapse = "|") %>%
#   str_replace_all(" ","[:blank:]")
laborVocabString <- laborVocab %>%
  paste(collapse = "|") %>%
  str_replace_all(" ","[:blank:]")

```

```{r daily data, echo=FALSE, warning=FALSE, message=FALSE}
#1/5/1981-9/9/2016

# INPUT FILES INTO R
daily_speechesFiles <- list.files(path="data/hein-daily/speeches",full.names=TRUE)
daily_descrFiles <- list.files(path="data/hein-daily/descr",full.names=TRUE)
daily_speechesFiles_update <- list.files(path="dataUpdates/data/txt_by_cr",full.names=TRUE)

# MERGE FILES
daily_speeches_old <- daily_speechesFiles %>%
  vroom(delim="|") 
daily_descr_old <- daily_descrFiles %>%
  vroom(delim="|")
daily_speeches_update <- daily_speechesFiles_update %>%
  vroom(delim="|") %>%
  filter(is.na(process)==TRUE) %>%
  select(-page,-process) %>%
  mutate(year=substr(date,1,4)) %>%
  mutate(speech=str_remove(speech,"^of[:space:](Alabama|Alaska|Arizona|Arkansas|California|Colorado|Connecticut|Delaware|Florida|Georgia|Hawaii|Idaho|Illinois|Indiana|Iowa|Kansas|Kentucky|Louisiana|Maine|Maryland|Massachusetts|Michigan|Minnesota|Mississippi|Missouri|Montana|Nebraska|Nevada|New Hampshire|New Jersey|New Mexico|New York|North Carolina|North Dakota|Ohio|Oklahoma|Oregon|Pennsylvania|Rhode Island|South Carolina|South Dakota|Tennessee|Texas|Utah|Vermont|Virginia|Washington|West Virginia|Wisconsin|Wyoming)"),
         speech= str_remove(speech,"^[^[:alpha:]]*")) ###***CH added

# COMBINE DESC + SPEECHES
daily_full_old <- daily_speeches_old %>%
  left_join(daily_descr_old) %>%
  select(speech_id,
         speech,
         chamber,
         date,
         speaker,
         file) %>%
  mutate(year=substr(date,1,4)) %>%
  filter(year!="2016")
  # filter(year>="1960" & year<="2015")


# COMBINE HEIN + UPDATED SPEECHES, COUNTS
daily_full <- daily_full_old %>%
  rbind(daily_speeches_update) %>%
  group_by(year) %>%
  mutate(total_annual_speeches=n()) %>%
  ungroup() %>%
  as.data.table()

#3841362

# CLEAN WORKSPACE
rm(daily_speeches_old,daily_descr_old,daily_speeches_update,daily_full_old)
gc()

# OUTPUT
# write_csv(daily_full,"data/hein-daily/daily_full.csv")
head(daily_full)

# CLEAN WORKSPACE
# rm(daily_full)

```

```{r bound data, echo=FALSE, warning=FALSE, message=FALSE}
#3/4/1983-12/22/2010

# INPUT FILES INTO R
bound_speechesFiles <- list.files(path="data/hein-bound/speeches",full.names=TRUE)
bound_descrFiles <- list.files(path="data/hein-bound/descr",full.names=TRUE)
# bound_byspeakerFiles <- list.files(path="data/hein-bound/byspeaker",full.names=TRUE)
# bound_bypartyFiles <- list.files(path="data/hein-bound/byparty",full.names=TRUE)
# bound_SpeakerMapFiles <- list.files(path="data/hein-bound/SpeakerMap",full.names=TRUE)

# MERGE FILES
bound_speeches <- bound_speechesFiles %>%
  vroom(delim="|")
bound_descr <- bound_descrFiles %>%
  vroom(delim="|") 

# COMBINE DESC + SPEECHES
bound_full <- bound_speeches %>%
  left_join(bound_descr) %>%
  select(speech_id,
         speech,
         chamber,
         date,
         speaker,
         file) %>%
  mutate(year=substr(date,1,4)) %>%
  filter(year<=1980) %>%
  # filter(year<=1980 & year>=1960) %>%
  group_by(year) %>%
  mutate(total_annual_speeches=n()) %>%
  ungroup() %>%
  as.data.table()
  # filter(grepl(enviroVocabString, speech, ignore.case = TRUE))
#13594354

# CLEAN WORKSPACE
rm(bound_speeches,bound_descr)
gc()

# OUTPUT
# write_csv(bound_full,"data/hein-bound/bound_full.csv")
head(bound_full)

# CLEAN WORKSPACE
# rm(bound_full)

```

```{r subset enviro, echo=FALSE, warning=FALSE, message=FALSE}

# SUBSET TO ENVIRO SPEECHES
Sys.time()
tic()
# old keywords: 91,651
# new keywords: 212,482
# new keywords2: 203,362
# daily_full_enviro_v1 <- daily_full %>%
#   filter(speech %ilike% enviroVocabString_v1) #3777
daily_full_enviro <- daily_full %>%
  filter(grepl("environmental", speech))
  # filter(speech %ilike% enviroVocabString) #71487 #
toc()

Sys.time()
tic()
# old keywords: 74,269
# new keywords: 435,539
# new keywords2: 426,345
# bound_full_enviro_v1 <- bound_full %>%
#   filter(speech %ilike% enviroVocabString_v1) #1668
bound_full_enviro <- bound_full %>%
  filter(grepl("environmental", speech))
  # filter(speech %ilike% enviroVocabString) #26282
toc()

```

```{r merge enviro, echo=FALSE, warning=FALSE, message=FALSE}

# MERGE ENVIRO
Sys.time()
tic()

# enviroSpeeches_v1 <- rbind(bound_full_enviro_v1,daily_full_enviro_v1) %>%
#   mutate(environment="Yes")

enviroSpeeches <- rbind(bound_full_enviro,daily_full_enviro) %>%
  mutate(environment="Yes")

# OUTPUT
# save(enviroSpeeches_v1,file="data/enviroSpeeches_v1.Rda")
# save(enviroSpeeches,file="data/enviroSpeeches.Rda")

toc()
```


```{r subset labor, echo=FALSE, warning=FALSE, message=FALSE}

# SUBSET TO LABOR SPEECHES
Sys.time()
tic()
# old keywords: 330,241
# new keywords: 367,447
# new keywords2: 367,126
# daily_full_labor_v1 <- daily_full %>%
#   filter(speech %ilike% laborVocabString_v1) #908
daily_full_labor <- daily_full %>%
  filter(speech %ilike% laborVocabString) #128422
toc()

Sys.time()
tic()
# old keywords: 375,851
# new keywords: 551,942
# new keywords2: 551,942
# bound_full_labor_v1 <- bound_full %>%
#   filter(speech %ilike% laborVocabString_v1) #1009
bound_full_labor <- bound_full %>%
  filter(speech %ilike% laborVocabString) #100395
toc()

```

```{r merge labor, echo=FALSE, warning=FALSE, message=FALSE}

# MERGE LABOR
Sys.time()
tic()

# laborSpeeches_v1 <- rbind(bound_full_labor_v1,daily_full_labor_v1) %>%
#   mutate(labor="Yes")
laborSpeeches <- rbind(bound_full_labor,daily_full_labor) %>%
  mutate(labor="Yes")


# OUTPUT
# save(laborSpeeches_v1,file="data/laborSpeeches_v1.Rda")
# save(laborSpeeches,file="data/laborSpeeches.Rda")

toc()

```

```{r merge all, echo=FALSE, warning=FALSE, message=FALSE}

# MERGE v1
# Sys.time()
# tic()
# enviroLaborSpeeches_v1 <- full_join(enviroSpeeches_v1,laborSpeeches_v1)
# save(enviroLaborSpeeches_v1,file="data/enviroLaborSpeeches_v1.Rda")
# fwrite(enviroLaborSpeeches_v1,"data/enviroLaborSpeeches_v1.csv")
# toc()

# MERGE v2
Sys.time()
tic()
enviroLaborSpeeches <- full_join(enviroSpeeches,laborSpeeches)
save(enviroLaborSpeeches,file="data/enviroLaborSpeeches.Rda")
fwrite(enviroLaborSpeeches,"data/enviroLaborSpeeches.csv")
toc()


```









```{r}

Sys.time()
tic()
daily_full_enviro <- daily_full %>%
  filter(grepl("environmental", speech)) #60107
  # filter(speech %ilike% enviroVocabString) #71487 
bound_full_enviro <- bound_full %>%
  filter(grepl("environmental", speech)) #21084
  # filter(speech %ilike% enviroVocabString) #26282 
toc()

Sys.time()
tic()
daily_full_labor <- daily_full %>%
  filter(grepl("\\blabor\\b", speech)) #45990
  # filter(speech %ilike% laborVocabString) #128422
bound_full_labor <- bound_full %>%
  filter(grepl("\\blabor\\b", speech))
  # filter(speech %ilike% laborVocabString) #100395
toc()

enviroSpeeches <- rbind(bound_full_enviro,daily_full_enviro) %>%
  mutate(environment="Yes")
laborSpeeches <- rbind(bound_full_labor,daily_full_labor) %>%
  mutate(labor="Yes")

enviroLaborSpeeches <- full_join(enviroSpeeches,laborSpeeches)
save(enviroLaborSpeeches,file="data/enviroLaborSpeeches.Rda")
fwrite(enviroLaborSpeeches,"data/enviroLaborSpeeches.csv")

```